### ISSUE TITLE
Problem with deserialization in Python 3

### ISSUE THREAD

**Issue by ihodes** [ikegami-yukino/shellinford-python#1]
We're running into this error when reading a save FM index in Python 3 (it works well in Python 2!)

```
index_contains_kmer
    for _ in fm.search(kmer):
SystemError: <built-in function delete_MapIntInt> returned a result with an error set
```

**Comment by ikegami-yukino** [comment]
Thanks for bug report.

This bug is fixed by https://github.com/ikegami-yukino/shellinford-python/commit/1196fa2b79474acd2a788b483a1543d90024180d

**Comment by ihodes** [comment]
Thank you! That was quick!
