### ISSUE TITLE
Build on Windows fail without including ctime library

### ISSUE THREAD

**Issue by LucaCerina** [ikegami-yukino/shellinford-python#10]
Hello,
I am building the library with VC++2019 build tools and it crashes on a undefined identifier 'time' when compiling shellinford_fm_index.cc

Including <ctime> to the source solved the problem

**Comment by ikegami-yukino** [comment]
@LucaCerina
Sorry for late.
I am busy now 💦
Please, wait a moment 🙇

**Comment by ikegami-yukino** [comment]
@LucaCerina 
This error occurred in an environment where multiple versions of Visual Studio were installed.
I resolved this error to use TotalUninstaller.
https://github.com/Microsoft/VisualStudioUninstaller/releases
